### PR TITLE
added BandCamp support

### PR DESCRIPTION
**Pull request by simon511000**

### CODE REVIEW

**Comment by simon511000** [comment]
I do not understand anything it's crazy

**Comment by Timeraa** [comment]
Working on an Presence "Store", when its done your presence will be tested and if working, added.

**Comment by simon511000** [comment]
thank you very much for your trust!

**Comment by davidmss2000** [comment]
> Working on an Presence "Store", when its done your presence will be tested and if working, added.

Who would be able to upload presences to the store?

**Comment by Timeraa** [comment]
Everyone, but they will be tested and added if they work.

**Comment by davidmss2000** [comment]
> Everyone, but they will be tested and added if they work.

That is very cool, good work

**Pull request closed without merging**
